<!DOCTYPE html>
<html>
<head>
	<title>QUnit Test Suite</title>
	<link rel="stylesheet" href="qunit-git.css" type="text/css" media="screen">
	<script type="text/javascript" src="qunit-git.js"></script>
	<!-- Your project file goes here -->
	<script type="text/javascript" src="$js_src_file$"></script>
	<!-- Your tests file goes here -->
	<script type="text/javascript" src="$js_test_file$"></script>
</head>
<body>
	<h1 id="qunit-header">QUnit Test Suite</h1>
	<h2 id="qunit-banner"></h2>
	<div id="qunit-testrunner-toolbar"></div>
	<h2 id="qunit-userAgent"></h2>
	<ol id="qunit-tests"></ol>
</body>
</html>
